### ISSUE TITLE
Checklist

### ISSUE THREAD

**Issue by sentinelweb** [TechForUK/simple-vote-ui#6]
**UI checklist**
https://docs.google.com/presentation/d/1Au4ePScA1KRQMTf1RK79V52cCHw6RjOdy70NSY4x17o/edit#slide=id.g56d0decf63_2_71

**Form fields**
https://docs.google.com/spreadsheets/d/1FVp0R5GSGdBSvlG3sxNcSNPK1Mnx688jXnwNhlnSbdo/edit#gid=1944616465

**messaging**
https://docs.google.com/document/d/1e2zoVeAGnKgNm2lfHIXDYNGz0QaufnXM-YMkLGRYsLk/edit?usp=sharing

**Site build**
- [x] Home page (Introduction)
- Basic Form (name/address data)
  - [x] basic data
  - [x] lookup electoral office address
  - UK
    - [x] form complete
  - EU 
    - [ ] Exclusion conditions (Merchant navy , ...)
- [x] Postal vote checkbox
   - [x] Postal vote validation
- [x] Signature field component
- [ ] Terms and conditions
- [ ] GDPR stuff
- [x] Data submit to node JS web app (simple-vote-api-2)
- [ ] google analytics
- [ ] captcha
- [ ] whatsapp sharing

**Extra** 
- [ ] Hosting 
   - [ ] subdomain setup on get voting
   - [ ] 404 page
   - [ ] SSL (should be ok as we will use get voting?)
- [ ] Readme
   - [ ] build instructions
   - [ ] configuration

**Comment by AugustinGrigorov** [comment]
this is no longer relevant will close
